apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: app
resources:
- ../../base
# 🔴 Jenkins 가 아래 newTag 를 :sha 로 커밋(§7.4). :latest 금지.
images:
- name: 192.168.0.10/mealplanning/mp-recipe-service
  newName: 192.168.0.10/mealplanning/mp-recipe-service
  newTag: c527f0c2f469b8fb9a6ceabf589c7d6fc7f2f825
