{
 "title": "Detail - Elasticsearch",
 "description": "Prometheus Elasticsearch Exporter with preconfigured dashboards.",
 "tags": [
  "food-budget-app",
  "data-systems",
  "detail",
  "elasticsearch"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "cluster",
    "query": {
     "query": "label_values(elasticsearch_indices_docs,cluster)"
    }
   },
   {
    "name": "name",
    "query": {
     "query": "label_values(elasticsearch_indices_docs{cluster=\"$cluster\"},name)"
    }
   }
  ]
 },
 "panels": [
  { "title": "KPI and Shards", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Cluster health",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "elasticsearch_cluster_health_status{cluster=\"$cluster\",color=\"red\"}==1 or (elasticsearch_cluster_health_status{cluster=\"$cluster\",color=\"green\"}==1)+4 or (elasticsearch_cluster_health_status{cluster=\"$cluster\",color=\"yellow\"}==1)+22"
    }
   ]
  },
  {
   "title": "Tripped for breakers",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "count(elasticsearch_breakers_tripped{cluster=\"$cluster\",name=~\"$name\"}>0) or vector(0)"
    }
   ]
  },
  {
   "title": "CPU usage Avg.",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (elasticsearch_process_cpu_percent{cluster=\"$cluster\",name=~\"$name\"} ) / count (elasticsearch_process_cpu_percent{cluster=\"$cluster\",name=~\"$name\"} )"
    }
   ]
  },
  {
   "title": "JVM memory used Avg.",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 10, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (elasticsearch_jvm_memory_used_bytes{cluster=\"$cluster\",name=~\"$name\"}) / sum (elasticsearch_jvm_memory_max_bytes{cluster=\"$cluster\",name=~\"$name\"}) * 100"
    }
   ]
  },
  {
   "title": "Nodes",
   "type": "stat",
   "description": "Number of nodes in the cluster",
   "gridPos": { "h": 3, "w": 2, "x": 14, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "elasticsearch_cluster_health_number_of_nodes{cluster=\"$cluster\"}"
    }
   ]
  },
  {
   "title": "Data nodes",
   "type": "stat",
   "description": "Number of data nodes in the cluster",
   "gridPos": { "h": 3, "w": 2, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "elasticsearch_cluster_health_number_of_data_nodes{cluster=\"$cluster\"}"
    }
   ]
  },
  {
   "title": "Pending tasks",
   "type": "stat",
   "description": "Cluster level changes which have not yet been executed",
   "gridPos": { "h": 3, "w": 2, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "elasticsearch_cluster_health_number_of_pending_tasks{cluster=\"$cluster\"}"
    }
   ]
  },
  {
   "title": "Open file descriptors per cluster",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (elasticsearch_process_open_files_count{cluster=\"$cluster\",name=~\"$name\"})"
    }
   ]
  },
  { "title": "Shards", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 } },
  {
   "title": "Active primary shards",
   "type": "stat",
   "description": "The number of primary shards in your cluster. This is an aggregate total across all indices.",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "elasticsearch_cluster_health_active_primary_shards{cluster=\"$cluster\"}"
    }
   ]
  },
  {
   "title": "Active shards",
   "type": "stat",
   "description": "Aggregate total of all shards across all indices, which includes replica shards",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "elasticsearch_cluster_health_active_shards{cluster=\"$cluster\"}"
    }
   ]
  },
  {
   "title": "Initializing shards",
   "type": "stat",
   "description": "Count of shards that are being freshly created",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "elasticsearch_cluster_health_initializing_shards{cluster=\"$cluster\"}"
    }
   ]
  },
  {
   "title": "Relocating shards",
   "type": "stat",
   "description": "The number of shards that are currently moving from one node to another node.",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "elasticsearch_cluster_health_relocating_shards{cluster=\"$cluster\"}"
    }
   ]
  },
  {
   "title": "Delayed shards",
   "type": "stat",
   "description": "Shards delayed to reduce reallocation overhead",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "elasticsearch_cluster_health_delayed_unassigned_shards{cluster=\"$cluster\"} "
    }
   ]
  },
  {
   "title": "Unassigned shards",
   "type": "stat",
   "description": "The number of shards that exist in the cluster state, but cannot be found in the cluster itself",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "elasticsearch_cluster_health_unassigned_shards{cluster=\"$cluster\"} "
    }
   ]
  },
  { "title": "Resources and Disk/Network", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "Load average",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "elasticsearch_os_load1{cluster=\"$cluster\",name=~\"$name\"}",
     "legendFormat": "load1: {{name}}"
    },
    {
     "expr": "elasticsearch_os_load5{cluster=\"$cluster\",name=~\"$name\"}",
     "legendFormat": "load5: {{name}}"
    },
    {
     "expr": "elasticsearch_os_load15{cluster=\"$cluster\",name=~\"$name\"}",
     "legendFormat": "load15: {{name}}"
    }
   ]
  },
  {
   "title": "CPU usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "elasticsearch_process_cpu_percent{cluster=\"$cluster\",name=~\"$name\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "JVM memory usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "elasticsearch_jvm_memory_used_bytes{cluster=\"$cluster\",name=~\"$name\"}",
     "legendFormat": "{{name}} used: {{area}}"
    },
    {
     "expr": "elasticsearch_jvm_memory_max_bytes{cluster=\"$cluster\",name=~\"$name\"}",
     "legendFormat": "{{name}} max: {{area}}"
    },
    {
     "expr": "elasticsearch_jvm_memory_pool_peak_used_bytes{cluster=\"$cluster\",name=~\"$name\"}",
     "legendFormat": "{{name}} peak used pool: {{pool}}"
    }
   ]
  },
  {
   "title": "Count of index segments",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "elasticsearch_indices_segments_count{cluster=\"$cluster\",name=~\"$name\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Disk usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "1-(elasticsearch_filesystem_data_available_bytes{cluster=\"$cluster\",name=~\"$name\"}/elasticsearch_filesystem_data_size_bytes{cluster=\"$cluster\",name=~\"$name\"})",
     "legendFormat": "{{name}}: {{path}}"
    }
   ]
  },
  {
   "title": "Network usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "irate(elasticsearch_transport_tx_size_bytes_total{cluster=\"$cluster\",name=~\"$name\"}[$__rate_interval])",
     "legendFormat": "{{name}}: sent "
    },
    {
     "expr": "-irate(elasticsearch_transport_rx_size_bytes_total{cluster=\"$cluster\",name=~\"$name\"}[$__rate_interval])",
     "legendFormat": "{{name}}: received"
    }
   ]
  },
  { "title": "Total Operations stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 } },
  {
   "title": "Total Operations  rate",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(elasticsearch_indices_indexing_index_total{cluster=\"$cluster\",name=~\"$name\"}[$__rate_interval])",
     "legendFormat": "{{name}}: indexing"
    },
    {
     "expr": "rate(elasticsearch_indices_search_query_total{cluster=\"$cluster\",name=~\"$name\"}[$__rate_interval])",
     "legendFormat": "{{name}}: query"
    },
    {
     "expr": "rate(elasticsearch_indices_search_fetch_total{cluster=\"$cluster\",name=~\"$name\"}[$__rate_interval])",
     "legendFormat": "{{name}}: fetch"
    },
    {
     "expr": "rate(elasticsearch_indices_merges_total{cluster=\"$cluster\",name=~\"$name\"}[$__rate_interval])",
     "legendFormat": "{{name}}: merges"
    },
    {
     "expr": "rate(elasticsearch_indices_refresh_total{cluster=\"$cluster\",name=~\"$name\"}[$__rate_interval])",
     "legendFormat": "{{name}}: refresh"
    },
    {
     "expr": "rate(elasticsearch_indices_flush_total{cluster=\"$cluster\",name=~\"$name\"}[$__rate_interval])",
     "legendFormat": "{{name}}: flush"
    },
    {
     "expr": "rate(elasticsearch_indices_get_exists_total{cluster=\"$cluster\",name=~\"$name\"}[$__rate_interval])",
     "legendFormat": "{{name}}: get_exists"
    },
    {
     "expr": "rate(elasticsearch_indices_get_missing_total{cluster=\"$cluster\",name=~\"$name\"}[$__rate_interval])",
     "legendFormat": "{{name}}: get_missing"
    },
    {
     "expr": "rate(elasticsearch_indices_get_total{cluster=\"$cluster\",name=~\"$name\"}[$__rate_interval])",
     "legendFormat": "{{name}}: get"
    },
    {
     "expr": "rate(elasticsearch_indices_indexing_delete_total{cluster=\"$cluster\",name=~\"$name\"}[$__rate_interval])",
     "legendFormat": "{{name}}: indexing_delete"
    }
   ]
  },
  {
   "title": "Total Operations time",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "irate(elasticsearch_indices_indexing_index_time_seconds_total{cluster=\"$cluster\",name=~\"$name\"}[$__rate_interval])",
     "legendFormat": "{{name}}: indexing"
    },
    {
     "expr": "irate(elasticsearch_indices_search_query_time_seconds{cluster=\"$cluster\",name=~\"$name\"}[$__rate_interval])",
     "legendFormat": "{{name}}: query"
    },
    {
     "expr": "irate(elasticsearch_indices_search_fetch_time_seconds{cluster=\"$cluster\",name=~\"$name\"}[$__rate_interval])",
     "legendFormat": "{{name}}: fetch"
    },
    {
     "expr": "irate(elasticsearch_indices_merges_total_time_seconds_total{cluster=\"$cluster\",name=~\"$name\"}[$__rate_interval])",
     "legendFormat": "{{name}}: merges"
    },
    {
     "expr": "irate(elasticsearch_indices_refresh_time_seconds_total{cluster=\"$cluster\",name=~\"$name\"}[$__rate_interval])",
     "legendFormat": "{{name}}: refresh"
    },
    {
     "expr": "irate(elasticsearch_indices_flush_time_seconds{cluster=\"$cluster\",name=~\"$name\"}[$__rate_interval])",
     "legendFormat": "{{name}}: flush"
    },
    {
     "expr": "irate(elasticsearch_indices_get_exists_time_seconds{cluster=\"$cluster\",name=~\"$name\"}[$__rate_interval])",
     "legendFormat": "{{name}}: get_exists"
    },
    {
     "expr": "irate(elasticsearch_indices_get_time_seconds{cluster=\"$cluster\",name=~\"$name\"}[$__rate_interval])",
     "legendFormat": "{{name}}: get_time"
    },
    {
     "expr": "irate(elasticsearch_indices_get_missing_time_seconds{cluster=\"$cluster\",name=~\"$name\"}[$__rate_interval])",
     "legendFormat": "{{name}}: get_missing"
    },
    {
     "expr": "irate(elasticsearch_indices_indexing_delete_time_seconds_total{cluster=\"$cluster\",name=~\"$name\"}[$__rate_interval])",
     "legendFormat": "{{name}}: indexing_delete"
    },
    {
     "expr": "irate(elasticsearch_indices_get_time_seconds{cluster=\"$cluster\",name=~\"$name\"}[$__rate_interval])",
     "legendFormat": "{{name}}: get"
    }
   ]
  }
 ]
}