apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: app
resources:
- ../../base
images:
- name: 192.168.0.10/mealplanning/mp-operations-service
  newName: 192.168.0.10/mealplanning/mp-operations-service
  newTag: d8b0033adb681b4c69a5412883e261ee1900cd2d
