apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: app
resources:
- ../../base
images:
- name: 192.168.0.10/mealplanning/mp-operations-service
  newName: 192.168.0.10/mealplanning/mp-operations-service
  newTag: cb4809c3098591522ff24ab259e49e7cc9c186a4
