apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: app
resources:
- ../../base
images:
- name: 192.168.0.10/mealplanning/mp-operations-service
  newName: 192.168.0.10/mealplanning/mp-operations-service
  newTag: 717b6f9ec65cd68c5c19621a2e02fa887a87164a
