apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: app
resources:
- ../../base
# 🔴 Jenkins 가 아래 newTag 를 :sha 로 커밋(§7.4). :latest 금지.
images:
- name: 192.168.0.10/mealplanning/mp-chat-service
  newName: 192.168.0.10/mealplanning/mp-chat-service
  newTag: 4edb8bd4468d488c4aaef0ea47a063470d9d4b84
