apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: app
resources:
- ../../base
# 🔴 Jenkins 가 아래 newTag 를 :sha 로 커밋(§7.4). :latest 금지.
images:
- name: 192.168.0.10/mealplanning/mp-chat-service
  newName: 192.168.0.10/mealplanning/mp-chat-service
  newTag: 2cecec5d4ef2809936f1a33c2a0e6a87de009fe8
