apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: app
resources:
- ../../base
# 🔴 Jenkins CD 가 newTag 를 :sha 로 커밋(§7.4). :latest 금지.
images:
- name: 192.168.0.10/mealplanning/mp-video-service
  newName: 192.168.0.10/mealplanning/mp-video-service
  newTag: 73c5e824c42579154f92a15dc408ac77b2347e7a
