apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: app
resources:
- ../../base
# 🔴 Jenkins 가 아래 newTag 를 :sha 로 커밋(§7.4). :latest 금지.
images:
- name: 192.168.0.10/mealplanning/mp-price-service
  newName: 192.168.0.10/mealplanning/mp-price-service
  newTag: 6e3274e74e6503db2f2573f0cf11da8b1ddb3512
