apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: app
resources:
- ../../base
# 🔴 Jenkins 가 아래 newTag 를 :sha 로 커밋(§7.4). :latest 금지.
images:
- name: 192.168.0.10/mealplanning/mp-pantry-service
  newName: 192.168.0.10/mealplanning/mp-pantry-service
  newTag: 397f2524070c29a29ad32d50a2a53e1ded9c63aa
